# Main

In [85]:
import pandas as pd
import numpy as np
import pingouin as pg

from scipy import stats

# Load Data

In [3]:
path_to_file = "/Users/brinkley97/Documents/development/lab-information_sciences_institute/datasets/tiles_dataset/"
name_of_file = "nurse_data.csv"
file = path_to_file + name_of_file

In [4]:
def load_data(file):
    original_data = pd.read_csv(file)
    # original_data = pd.DataFrame(file)
    copy_of_data = original_data.copy()
    return copy_of_data

In [22]:
nurse_df = load_data(file)
nurse_df

,MitreID,participant_id,abs,vocab,gats_Status,gats_Quantity,gats_Quantity_Sub,audit,psqi,ipaq,...,SmartPhone,Gender,Shift,Wave,DropoutDate,Age,Educ,job,native_lang,PSQI
0,SG1025,02581754-36cd-4b23-85ea-bf995c6dec83,15,29,current,6.0,6.0,7.0,7.0,26308.0,...,iPhone,Male,Night shift,2,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
1,SD1003,02b7a595-6508-46bd-8239-6deb433d6290,17,35,never,0.0,NaN,1.0,7.0,9522.0,...,Android,Female,Day shift,1,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
2,SG1033,05dedb61-63bc-44e3-8e28-a5d32d91f7e9,20,40,past,0.0,NaN,1.0,9.0,943.0,...,iPhone,Male,Night shift,2,NaN,>= 40 Years,Some college or College,nurse,No,PSQI >= 7
3,SG1005,06b33ec4-706d-462f-a681-05491be38eb3,16,31,never,0.0,NaN,1.0,4.0,5682.0,...,Android,Male,Night shift,1,NaN,>= 40 Years,Graduate,nurse,No,PSQI < 7
4,SY1004,0adb7679-9d26-46e7-a134-11da293910f3,15,36,never,0.0,NaN,0.0,4.0,8533.0,...,Android,Male,Day shift,1,NaN,>= 40 Years,Some college or College,nurse,Yes,PSQI < 7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,SD1068,f610ffea-f6cb-4182-bbe7-19ff8fbe66ee,20,33,never,0.0,NaN,1.0,10.0,3145.5,...,iPhone,Female,Day shift,2,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
109,SD1099,f732e878-e538-49b8-97d3-49ca29e9a3f8,13,33,never,0.0,NaN,1.0,5.0,6475.5,...,iPhone,Female,Day shift,3,NaN,>= 40 Years,Some college or College,nurse,No,PSQI < 7
110,SD1129,fabef151-53c8-4a46-9897-0180868a53f5,14,33,past,0.0,NaN,1.0,7.0,15100.5,...,Android,Male,Day shift,3,NaN,>= 40 Years,Some college or College,nurse,No,PSQI >= 7
111,SY1006,fae38580-1e2d-4491-9de5-7b75703ba4ce,15,35,never,0.0,NaN,5.0,9.0,15908.0,...,Android,Male,Day shift,1,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
112,SD1015,fcb14a4c-1ffa-4315-872a-a38833459885,17,30,never,0.0,NaN,0.0,4.0,NaN,...,iPhone,Female,Day shift,1,NaN,>= 40 Years,Some college or College,nurse,Yes,PSQI < 7

In [28]:
day_shift = nurse_df['Shift'] == 'Day shift'
day_df = nurse_df.loc[day_shift]
day_df.head(5)

,MitreID,participant_id,abs,vocab,gats_Status,gats_Quantity,gats_Quantity_Sub,audit,psqi,ipaq,...,SmartPhone,Gender,Shift,Wave,DropoutDate,Age,Educ,job,native_lang,PSQI
1,SD1003,02b7a595-6508-46bd-8239-6deb433d6290,17,35,never,0.0,NaN,1.0,7.0,9522.0,...,Android,Female,Day shift,1,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
4,SY1004,0adb7679-9d26-46e7-a134-11da293910f3,15,36,never,0.0,NaN,0.0,4.0,8533.0,...,Android,Male,Day shift,1,NaN,>= 40 Years,Some college or College,nurse,Yes,PSQI < 7
5,SD1084,0bf54591-e0ac-47ba-9b43-31ff54dfcee8,16,23,never,0.0,NaN,0.0,6.0,10263.0,...,iPhone,Female,Day shift,2,NaN,< 40 Years,Some college or College,nurse,No,PSQI < 7
7,SD1072,0e615090-ca26-4635-9590-f6e6cde1094f,17,35,never,0.0,NaN,4.0,9.0,25584.0,...,iPhone,Female,Day shift,2,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
9,SD1002,0ec84778-1a98-4cd7-aa11-05997ddadd52,12,32,never,0.0,NaN,1.0,6.0,17880.0,...,iPhone,Female,Day shift,1,NaN,>= 40 Years,Some college or College,nurse,No,PSQI < 7

In [30]:
night_shift = nurse_df['Shift'] == 'Night shift'
night_df = nurse_df.loc[night_shift]
night_df.head(5)

,MitreID,participant_id,abs,vocab,gats_Status,gats_Quantity,gats_Quantity_Sub,audit,psqi,ipaq,...,SmartPhone,Gender,Shift,Wave,DropoutDate,Age,Educ,job,native_lang,PSQI
0,SG1025,02581754-36cd-4b23-85ea-bf995c6dec83,15,29,current,6.0,6.0,7.0,7.0,26308.0,...,iPhone,Male,Night shift,2,NaN,< 40 Years,Some college or College,nurse,Yes,PSQI >= 7
2,SG1033,05dedb61-63bc-44e3-8e28-a5d32d91f7e9,20,40,past,0.0,NaN,1.0,9.0,943.0,...,iPhone,Male,Night shift,2,NaN,>= 40 Years,Some college or College,nurse,No,PSQI >= 7
3,SG1005,06b33ec4-706d-462f-a681-05491be38eb3,16,31,never,0.0,NaN,1.0,4.0,5682.0,...,Android,Male,Night shift,1,NaN,>= 40 Years,Graduate,nurse,No,PSQI < 7
6,SG1018,0e33f78a-7064-44ff-a8a4-711f99113d39,13,29,never,0.0,NaN,0.0,7.0,9252.0,...,iPhone,Female,Night shift,2,NaN,>= 40 Years,Some college or College,nurse,No,PSQI >= 7
8,SG1029,0ebe238f-34a9-47f5-a04b-5b059e45e4a5,18,30,never,0.0,NaN,1.0,7.0,10620.0,...,Android,Female,Night shift,2,NaN,>= 40 Years,Some college or College,nurse,No,PSQI >= 7

# Load Generated Specific Questions

In [7]:
path_to_questions = "/Users/brinkley97/Documents/development/lab-information_sciences_institute/datasets/tiles_dataset/"
name_of_questions = "generateSpecificQuestions.ipynb"
questions = path_to_questions + name_of_questions

In [8]:
# %load questions
/Users/brinkley97/Documents/development/lab-information_sciences_institute/datasets/tiles_dataset/generateSpecificQuestions.ipynb

In [137]:
%run "generateSpecificQuestions.ipynb"

group_1  ::  day-shift
group_2  ::  night-shift
demographic  ::  {'Gender': ['Female', 'Male'], 'Age': ['< 40 Years', '>= 40 Years'], 'Educ': ['Some college or College', 'Graduate'], 'native_lang': ['English', 'non-english']}
behavioral  ::  ['stai', 'pan_PosAffect', 'pan_NegAffect', 'swls', 'bfi_Neuroticism', 'bfi_Conscientiousness', 'bfi_Extraversion', 'bfi_Agreeableness', 'bfi_Openness', 'psqi']
physiological  ::  ['step count', 'heart rate', 'sleep', 'average rest-activity ratio', 'average walk activity ratio', 'average vigorous activity duration']
demo_vars :  [['Gender', 'Age', 'Educ', 'native_lang'], ['Female', 'Male', '< 40 Years', '>= 40 Years', 'Some college or College', 'Graduate', 'English', 'non-english']]

In [138]:
demo_specific_questions = list(t_test_questions.values())[0]
demo_specific_questions

['what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Gender* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Age* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Educ* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *native_lang* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Female* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Male* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *< 40 Years* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *>= 40 Years* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Some college or College* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Graduate* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *English* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *non-english* ?']

# Run analysis

## Fisher Odds Test - Table 1

In [61]:
def fisher_odds_p_value(first_df, second_df, demo, demo_option1, demo_option2, print_col):
    tabel_df = pd.DataFrame(index=['day', 'night'], columns=[demo_option1, demo_option2])
    tabel_df.loc['day', demo_option1] = len(first_df.loc[first_df[demo] == demo_option1])
    tabel_df.loc['day', demo_option2] = len(first_df.loc[first_df[demo] == demo_option2])
    tabel_df.loc['night', demo_option1] = len(second_df.loc[second_df[demo] == demo_option1])
    tabel_df.loc['night', demo_option2] = len(second_df.loc[second_df[demo] == demo_option2])
    oddsratio, pvalue = stats.fisher_exact(np.array(tabel_df))
    print(tabel_df)
    # print()
    
    return 'oddsratio : %.3f, pvalue: %.3f \n' % (oddsratio, pvalue)

In [62]:
def table_one_demo(demo_specific_questions):
    key_words = []

    for demo_specific_question in demo_specific_questions:
        print(demo_specific_question)
        demos = list(key_words_in_study["demographic"])
        # print(demos)
        demo_values = list(key_words_in_study.values())[2]
        # print("demo_values : ", demo_values)
        for demo in demos:
            # print(demo)
            if demo in demo_specific_question.split("*"):
                # print(demo, True)
                demo_option1 = demo_values[demo][0]
                # print("demo_option1 : ", demo_option1)
                demo_option2 = demo_values[demo][1]
                # print("demo_option2 : ", demo_option2)
                p_value = fisher_odds_p_value(day_df, night_df, demo=demo, demo_option1=demo_option1, demo_option2=demo_option2, print_col=demo)
                # print(p_value)
            else:
                continue
        print("")
    return

In [63]:
table_one_demo(demo_specific_questions)

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Gender* ?
      Female Male
day       51   18
night     31   13

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Age* ?
      < 40 Years >= 40 Years
day           40          29
night         32          12

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Educ* ?
      Some college or College Graduate
day                        59       10
night                      33       11

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *native_lang* ?
      English non-english
day         0           0
night       0           0

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Female* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Male* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *< 40 Years* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *>= 40 Years* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Some college or College* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *Graduate* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *English* ?

what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *non-english* ?

In [139]:
behav_specific_questions = list(t_test_questions.values())[1]
behav_specific_questions

['what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *stai* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *pan_PosAffect* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *pan_NegAffect* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *swls* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Neuroticism* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Conscientiousness* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Extraversion* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Agreeableness* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Openness* ?',
 'what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *psqi* ?']

In [143]:
def ttest_p_value(all_df, first_df, second_df, demo, print_col, end=False, stat='num'):

#     # print('\multicolumn{1}{l|}{\\hspace{0.5cm}{%s}} &' % print_col)
#     print('\multicolumn{1}{l|}{{%s}} &' % print_col)
#     stats_df = pd.DataFrame(index=[demo])

#     if stat != 'num':
#         len1 = len(first_df.loc[first_df[demo] == demo_option])
#         per1 = (len(first_df.loc[first_df[demo] == demo_option]) / len(first_df) * 100)
#         len2 = len(second_df.loc[second_df[demo] == demo_option])
#         per2 = (len(second_df.loc[second_df[demo] == demo_option]) / len(second_df) * 100)
#         len_all = len(all_df.loc[all_df[demo] == demo_option])
#         per_all = (len(all_df.loc[all_df[demo] == demo_option]) / len(all_df) * 100)

#         print('\multicolumn{1}{c|}{{%d (%.1f\\%%)}} &' % (len1, per1))
#         print('\multicolumn{1}{c|}{{%d (%.1f\\%%)}} &' % (len2, per2))
#         print('\multicolumn{1}{c|}{{%d (%.1f\\%%)}} &' % (len_all, per_all))
#         print('\multicolumn{1}{c|}{} &')
#         print('\multicolumn{1}{c}{} \\rule{0pt}{2.25ex} \\\\')
#     else:
#         mean1 = np.nanmean(first_df[demo])
#         std1 = np.nanstd(first_df[demo])
#         mean2 = np.nanmean(second_df[demo])
#         std2 = np.nanstd(second_df[demo])
#         mean_all = np.nanmean(all_df[demo])
#         std_all = np.nanstd(all_df[demo])
#         min = np.nanmin(all_df[demo])
#         max = np.nanmax(all_df[demo])

#         praint('\multicolumn{1}{c|}{{%.1f $\\pm$ %.1f}} &' % (mean1, std1))
#         print('\multicolumn{1}{c|}{{%.1f $\\pm$ %.1f}} &' % (mean2, std2))
#         print('\multicolumn{1}{c|}{{%.1f $\\pm$ %.1f}} &' % (mean_all, std_all))
#         print('\multicolumn{1}{c|}{{%.1f - %.1f}} &' % (min, max))

#         # u_stats, p = stats.mannwhitneyu(first_df[demo].dropna(), second_df[demo].dropna())
#         # result = pg.mwu(first_df[demo].dropna(), second_df[demo].dropna(), tail='two-sided')
        result = pg.ttest(np.array(first_df[demo].dropna()), np.array(second_df[demo].dropna()))
        print(result)
#         # lm = ols(demo + ' ~ Shift', data=all_df).fit()
#         # result = sm.stats.anova_lm(lm, typ=2)  # Type 2 ANOVA DataFrame

#         p = result['p-val'].values[0]
#         t = result['T'].values[0]
#         df = result['dof'].values[0]


#         stats_df['p'] = p
#         stats_df['T'] = t
#         stats_df['df'] = df

#         if p < 0.01: print('\multicolumn{1}{c}{$\mathbf{%.3f^{**}}$} \\rule{0pt}{2.25ex} \\\\' % (p))
#         elif p < 0.05: print('\multicolumn{1}{c}{$\mathbf{%.3f^*}$} \\rule{0pt}{2.25ex} \\\\' % (p))
#         else: print('\multicolumn{1}{c}{$%.3f$} \\rule{0pt}{2.25ex} \\\\' % (p))

#     if end == True: print('\\hline')
#     print()
#     return stats_df

In [148]:
def table_one_behav(behav_specific_questions):
    behav_values = list(key_words_in_study.values())[3]
    print("behav_values : ", behav_values)
    
    for behav_specific_question in behav_specific_questions:
        print("\n", behav_specific_question)
        behavs = list(key_words_in_study["behavioral"])
        # print(behavs)
        
        for behav in behavs:
            print("\nbehav : ", behav)
            
            if behav in behav_specific_question.split("*"):
                p_value = ttest_p_value(nurse_df, day_df, night_df, behav, behav, end=False, stat='num')

In [149]:
table_one_behav(behav_specific_questions)

behav_values :  ['stai', 'pan_PosAffect', 'pan_NegAffect', 'swls', 'bfi_Neuroticism', 'bfi_Conscientiousness', 'bfi_Extraversion', 'bfi_Agreeableness', 'bfi_Openness', 'psqi']

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *stai* ?

behav :  stai
               T        dof alternative     p-val          CI95%   cohen-d  \
T-test -1.528672  79.854615   two-sided  0.130297  [-5.86, 0.77]  0.306817

         BF10     power
T-test  0.578  0.350924

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *pan_PosAffect* ?

behav :  stai

behav :  pan_PosAffect
              T        dof alternative     p-val          CI95%   cohen-d  \
T-test -0.30094  89.635445   two-sided  0.764157  [-2.92, 2.15]  0.058461

         BF10     power
T-test  0.213  0.060401

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *pan_NegAffect* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect
               T        dof alternative     p-val         CI95%   cohen-d  \
T-test -1.873858  73.804357   two-sided  0.064908  [-3.39, 0.1]  0.384309

         BF10     power
T-test  0.971  0.505946

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *swls* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls
               T        dof alternative     p-val         CI95%   cohen-d  \
T-test  2.208651  72.538323   two-sided  0.030359  [0.05, 1.07]  0.456011

         BF10     power
T-test  1.769  0.646681

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Neuroticism* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism
              T        dof alternative     p-val          CI95%  cohen-d  \
T-test -1.39753  91.036483   two-sided  0.165651  [-0.44, 0.08]  0.27024

         BF10     power
T-test  0.488  0.284297

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Conscientiousness* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness
               T        dof alternative     p-val          CI95%   cohen-d  \
T-test  0.524634  90.387746   two-sided  0.601122  [-0.18, 0.31]  0.101665

         BF10     power
T-test  0.231  0.081807

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Extraversion* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion
               T        dof alternative     p-val          CI95%   cohen-d  \
T-test  0.526318  82.034222   two-sided  0.600088  [-0.21, 0.35]  0.104853

         BF10     power
T-test  0.231  0.083866

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Agreeableness* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness
               T       dof alternative     p-val          CI95%  cohen-d  \
T-test -0.006964  99.17521   two-sided  0.994457  [-0.18, 0.18]  0.00131

         BF10     power
T-test  0.204  0.050005

behav :  bfi_Openness

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *bfi_Openness* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness
               T        dof alternative    p-val          CI95%   cohen-d  \
T-test -1.916975  93.939674   two-sided  0.05828  [-0.46, 0.01]  0.367148

         BF10     power
T-test  1.043  0.470814

behav :  psqi

 what are differences in primarily *day-shift* nurses and primarily *night-shift* nurses for *psqi* ?

behav :  stai

behav :  pan_PosAffect

behav :  pan_NegAffect

behav :  swls

behav :  bfi_Neuroticism

behav :  bfi_Conscientiousness

behav :  bfi_Extraversion

behav :  bfi_Agreeableness

behav :  bfi_Openness

behav :  psqi
              T        dof alternative     p-val           CI95%   cohen-d  \
T-test -2.97032  72.434393   two-sided  0.004033  [-2.27, -0.45]  0.613283

         BF10     power
T-test  9.703  0.878777